token = "token" # Token of your bot (https://discord.dev)
bot_admins = ["611468402263064577", "483189540622958593"] # The admins of the bot (have BOT_ADMIN permission)

[emojis] # The emojis of the bot
success = "<a:check:879378363729465385>"
error = "<a:cross:879378363653967983>"
loading = "<a:loading:879378363616231444>"

[channels] # The channels for logs
moderation_logs = "877472410943782932"

[colors] # The colors for embeds
red= "#ff0004"
orange= "ff8400"
green= "#02ff30"